spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC
      username: postgres
      password: ghtjq2959@
      driver-class-name: org.postgresql.Driver
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect