num_1 = input('First number is: ')
num_2 = input('Second number is: ')
user_sum = float(num_1) + float(num_2)
# print("The sum of: " + num_1 + " and " + num_2 + " is " + user_sum)
print("The sum of " + str(float(num_1)) + " and " + str(float(num_2)) + " is " + str(user_sum))