server:
  port: 8080


logging:
  level:
    root: info
  charset:
    file:
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/local
  webflux:
    hiddenmethod:
      filter:
        enabled:
          true: