version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always