### GET request to example server
GET http://localhost:8080/request-param?username=hello&age=20&username=hello2

###

POST http://localhost:8080/request-body-json
Content-Type: application/json

{
  "username": "kim",
  "age": 37
}