spring:
    datasource:
        hikari:
            maximum-pool-size: 30
            connection-timeout: 5000
            auto-commit: false
        url: "jdbc:mysql://localhost:3306/book_manager"
        username: "root"
        password: "ghtjq2959@"
        driver-class-name: "com.mysql.cj.jdbc.Driver"
    jpa:
        hibernate:
            ddl-auto: create
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    output:
        ansi:
            enabled: always
logging:
    level:
        org.springframework.web: debug
#        org.hibernate.type: trace