spring:
  application:
    name: actuator-start

server:
  port: 8080
  tomcat:
    threads:
      max: 200

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

logging:
  level:
    com.example.actuatorstart.controller: trace